# Define o nome do Workflow
name: Fluxo Padrão

# Define quando o Workflow será disparado
on:
  push:
    branches: [ "main","tst","dev" ]
  pull_request:
    branches: [ "main" ]

  # Habilita rodar manualmente
  workflow_dispatch:

# Define os jobs que o Workflow executará
jobs:
  test_job:
    name: executando teste de job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        uses: docker/login-action@v3.3.0
        with:     
          username: 'marlaamooury'
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.11.0
        with:
          context: .
          tags: 'marlaamooury/tc-fase2:latest'
          push: true
