name: Fluxo padrão
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Docker Login 
              uses: docker/login-action@v3.0.0
              with:
                username: 'zennbyte'
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and Push Docker images
              uses: docker/build-push-action@v6.9.0
              with:
                context: .
                tags: 'zennbyte/api-contactmanager:latest'
                push: true
          
