# Define o nome do Workflow
name: CICD

on:
  push:
    branches: [ "main","tst","dev" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test_job:
    name: executando teste de job
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v2
        
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:     
          username: 'marlaamooury'
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.11.0
        with:
          context: .
          tags: 'marlaamooury/tc-fase2:latest'
          push: true
